# Sprint　深層学習スクラッチ　畳み込みニューラルネットワーク１

In [2]:
import numpy as np
import random
import pandas as pd
from numpy import linalg as LA
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split # testとtrain分割
from sklearn.metrics import accuracy_score
import math

In [ ]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
print("X_train{}".format(X_train.shape)) # (60000, 28, 28)
print("X_test{}".format(X_test.shape)) # (10000, 28, 28)
print("y_train{}".format(y_train.shape))# (60000,)
print("y_test{}".format(y_test.shape))#(10000, )
print(X_train[0].dtype) # uint8

In [ ]:
# (1, 28, 28)の各画像を、(1, 784)に変換
X_train = X_train.reshape(-1, 784)
X_test = X_test.reshape(-1, 784)

In [ ]:
X_train = X_train.astype(np.float)
X_test = X_test.astype(np.float)
X_train /= 255 # 全て２５５で割っている
X_test /= 255
print(X_train.max()) # 1.0
print(X_train.min()) # 0.0

### 【問題1】チャンネル数を1に限定した1次元畳み込み層クラスの作成

In [ ]:
class SimpleInitializer:#⭐️iinitializerの渡し方？？実装あってる？？
    """
    様々な関数による初期化
    Parameters
    ----------
    sigma : float
      ガウス分布の標準偏差
    """
    def __init__(self):
#         self.Xavier = Xavier
#         self.HeInitia = HeInitia
#         self.sigma = sigma
        pass

    # XavierInitializerクラス
    def _XavierInitializer(self, n_nodes1):
        Xavier = 1/math.sqrt(n_nodes1)
        
    # HeInitializerクラス
    def _HeInitializer(self, n_nodes1):
        HeInitia = math.sqrt(2/n_nodes1)

    # sigmaクラス
    def _Sigma(self):
        δ = self.sigma
    
    def W(self, n_nodes1, n_nodes2):
        """
        重みの初期化
        Parameters
        ----------
        n_nodes1 : int
          前の層のノード数
        n_nodes2 : int
          後の層のノード数

        Returns
        ----------
        W :
        """
        # W(重み)の初期値を用意
        
        if self.initializer == "Xavier":
            self.initializer = _XavierInitializer(n_nodes1)
        elif self.initializer == "Helnitia":
            self.initializer = _HeInitializer(n_nodes1)
        elif self.initializer == "Sigma"
            self.initializer = _Sigma
        
        self.W = self.itializer * np.random.randn(n_nodes1, n_nodes2)
        return W
    
    def B(self, n_nodes2):
        """
        バイアスの初期化
        Parameters
        ----------
        n_nodes2 : int
          後の層のノード数

        Returns
        ----------
        B :
        """
        # B(バイアス)の形を用意
        self.B = self.itializer * np.random.randn(self.n_nodes2)
        return B

In [51]:
class SimpleConv1d:
    #def __init__(self, itializer):
        #self.initializer = initializer


    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes1)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes2)
            出力
        """
        N_in = len(X)
        P = 1
        F = 3
        S = 1
        
        N_out = (N_in + 2*P - F)/S +1
        
        indexes = np.empty((0, len(X)))

        for i in range(self.N_out):
            a = np.arange(len(X))
            a = a[i : i + len(self.W)]
            a = a[np.newaxis,:]
            indexes = np.append(indexes, a, axis=0).astype(np.int)
            #print(indexes.shape)
            
        A = X[indexes]@self.W + 1
        return A
    
    def backward(self, dA):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """
        indexes = np.empty((0, len(self.W)))
        #print(indexes.shape)

        for i in range(self.N_out):
            a = np.arange(len(X))
            a = a[i : len(self.W)+i]
            a = a[np.newaxis, :]
            indexes = np.append(indexes, a, axis=0).astype(np.int)
            print(indexes.shape)
        
        #gradientLW = gradientLA@X[indexes] gradientLA=dA??⭐️
        gradientLW = dA@X[indexes]
        
        gradientLB = np.sum(dA[: self.N_output-1]) # 確かめ算OK
        
        #gradientLX = 
        

SyntaxError: invalid syntax (<ipython-input-51-05a22bf0b6ff>, line 59)

### 【問題2】1次元畳み込み後の出力サイズの計算

In [58]:
# N_out：出力のサイズ（特徴量）
# N_in：入力のサイズ（特徴量）
# P：パディングの数
# F:フィルタのサイズ
# S:ストライドのサイズ

X = np.array([1, 2, 3, 4])
w = np.array([3, 5, 7])

N_in = len(X)
P = 1
F = 3
S = 1

N_out = (N_in + 2*P - F)/S +1

print("入力サイズ：{}".format(N_in))
print("パディング数：{}".format(P))
print("フィルタサイズ：{}".format(F))
print("ストライドサイズ：{}".format(S))
print("出力のサイズ：{}".format(N_out))

入力サイズ：4
パディング数：1
フィルタサイズ：3
ストライドサイズ：1
出力のサイズ：4.0


### 【問題3】小さな配列での1次元畳み込み層の実験

In [4]:
X = np.array([1, 2, 3, 4])
w = np.array([3, 5, 7])

In [67]:
#インデックスを作成
indexes = np.empty((0, len(w)))
print(indexes.shape)

for i in range(2):
    index = np.arange(len(X))[np.newaxis, :]
    index = index[:, i : (i +len(w))]#フィルタ分スライシングしてずらしていく
    print(index.shape)
    indexes = np.append(indexes, index, axis=0).astype(np.int)
print("X.shape{}".format(X.shape))
print("indexes.shape{}".format(indexes.shape))
print("X[indexes]\n{}".format(X[indexes]))
a = X[indexes]@w + 1

print(a)

(0, 3)
(1, 3)
(1, 3)
X.shape(4,)
indexes.shape(2, 3)
X[indexes]
[[1 2 3]
 [2 3 4]]
[35 50]


In [64]:
#インデックスを作成
indexes = np.empty((0, len(w)))
print(indexes.shape)
index = np.arange(len(X))[np.newaxis, :]
index_copy = index.copy()
#print(index.shape)
for i in range(2):
    index = index_copy[:, i : (i +len(w))]
    print(index)
    indexes = np.append(indexes, index, axis=0).astype(np.int)
print(indexes.shape)
print(X[indexes])
a = X[indexes]@w + 1

print(a)

(0, 3)
[[0 1 2]]
[[1 2 3]]
(2, 3)
[[1 2 3]
 [2 3 4]]
[35 50]


In [49]:
a = np.array([0,1,2,3])
b = a[0:3]
print(b)

[0 1 2]


In [6]:
#小さな配列X、wを入力して、SimpleConv1dをインスタンス化、フォワードプロパゲーションを実行
# フォワードプロパゲーションの正解出力
# a = np.array([35, 50])

S1 = SimpleConv1d()
a = S1.forward(X, w)
print(a)

NameError: name 'SimpleConv1d' is not defined

In [7]:
#誤差
# delta_a = np.array([10, 20])

#バックプロパゲーション
#delta_b = np.array([30])
#delta_w = np.array([50, 80, 110])
#delta_x = np.array([30, 110, 170, 140])


In [30]:
class AdaGrad:
    """
    確率的勾配降下法
    Parameters
    ----------
    lr : 学習率
    """
    def __init__(self, lr=0.1):
        self.lr = lr
    def update(self, layer):
        """
        ある層の重みやバイアスの更新
        Parameters
        ----------
        layer : 更新前の層のインスタンス

        Returns
        ----------
        layer : 更新後の層のインスタンス
        """
        
        HW = HW + np.mean(layer.gradientLW, axis=0)**2
        HB = HB + np.mean(layer.gradientLB, axis=0)**2
        
        #Wの更新式
        layer.W = layer.W - self.lr/math.sqrt(HW)*np.mean(layer.gradientLW)
        
        # Bの更新式
        layer.B = layer.B - self.lr/ma.sqrt(HB)*np.mean(layer.gradientLB)
        
        return layer #参照渡しのため、なくてもよい

In [ ]:
class SGD:
    """
    確率的勾配降下法
    Parameters
    ----------
    lr : 学習率
    """
    def __init__(self, lr=0.1):
        self.lr = lr
    def update(self, layer):
        """
        ある層の重みやバイアスの更新
        Parameters
        ----------
        layer : 更新前の層のインスタンス

        Returns
        ----------
        layer : 更新後の層のインスタンス
        """
        
        #Wの更新式
        layer.W = layer.W - layer.gradientLW*self.lr
        
        # Bの更新式
        layer.B = layer.B - layer.gradientLB*self.lr
        
        #return layer #参照渡しのため、なくてもよい

In [43]:
n_output = 10
dA = np.arange(10)
print(dA)

#for i in range(n_output-1):
gradientLB = np.sum(dA[: n_output-1])
    
print(gradientLB)

[0 1 2 3 4 5 6 7 8 9]
36


In [6]:
a = []
for s in range(len(w)-1):
    for i in range(len(x)):
        a = np.sum(x[i + s]*w[s] + 1)
    a = np.append(a, a)
printi(a)

IndexError: index 4 is out of bounds for axis 0 with size 4

In [42]:
a = np.arange(9)
print(a)
print(np.sum(a))

[0 1 2 3 4 5 6 7 8]
36


In [62]:
X = np.array([1, 2, 3, 4,5,6,7,8,9,10,11,12,13,14,15])
w = np.array([3, 5, 7])

indexes = np.empty((0, len(w)))
#print(indexes.shape)

for i in range(len(X)-2):
    a = np.arange(len(X))
    a = a[i : i+len(w)]
    a = a[np.newaxis, :]
    indexes = np.append(indexes, a, axis=0).astype(np.int)
print(indexes)

#gradientLW = gradientLA@X[indexes] gradientLA=dA??⭐️
#gradientLW = dA@X[indexes]

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]
