# Week2授業前課題　行列積のスクラッチ

In [58]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


### 【問題1】行列積を手計算する

In [59]:
ab_1_1 = -1*0 + 2*0 + 3*2
ab_1_2 = -1*2 + 2*2 + 3*9
ab_1_3 = -1*1 + 2*-8 + 3*-1
ab_2_1 = 4*0 + 5*0 + 6*2
ab_2_2 = 4*2 + -5*2 + 6*9
ab_2_3 = 4*1 + -5*-8 + 6*-1
ab_3_1 = 7*0 + 8*0 +-9*2
ab_3_2 = 7*2 + 8*2 + -9*9
ab_3_3 = 7*1 + 8*-8 + -9*-1

matrix_AB = [[ab_1_1, ab_1_2, ab_1_3],
             [ab_2_1, ab_2_2, ab_2_3],
             [ab_3_1, ab_3_2, ab_3_3]]

print("行列ABの積は\n{}".format(matrix_AB))

行列ABの積は
[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


### 【問題2】NumPyの関数による計算

In [60]:
# np.matmul()
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

matmul_ab = np.matmul(a_ndarray, b_ndarray)
print("np.matmul()による計算\n{}".format(matmul_ab))

# np.dot()
dot_ab = np.dot(a_ndarray, b_ndarray)
print("np.dot()による計算\n{}".format(dot_ab))

# @演算子
print("@演算子による計算\n{}".format(a_ndarray @ b_ndarray))


np.matmul()による計算
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
np.dot()による計算
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
@演算子による計算
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 【問題3】ある要素の計算を実装

In [61]:
# 行列AB
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

matrix_a0_b0 = np.sum(a_ndarray[0,:]*b_ndarray[:,0])
print(matrix_a0_b0)

6


### 【問題4】行列積を行う関数の作成

In [62]:
# for文で行列積を求める関数を作成
def compute_matrix_product(matrix_1, matrix_2):
    matrix_1_shape = matrix_1.shape # 1つ目の行列の形
    matrix_2_shape = matrix_2.shape
    matrix_product_list = []
    i = 0
    j = 0

    for i in range(matrix_1_shape[0]):
        for j in range(matrix_2_shape[1]):
                matrix_product = np.sum(matrix_1[i,:]*matrix_2[:,j])
                matrix_product_list.append(matrix_product)
    matrix_product_re = np.reshape(matrix_product_list,(matrix_1_shape[0], matrix_2_shape[1]))
    return matrix_product_re

# 行列AB
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

compute_matrix_product(matrix_1 = a_ndarray, matrix_2 = b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### 【問題5】計算が定義されない入力を判定する

In [63]:
# for文で行列積を求める関数を作成
def compute_matrix_product(matrix_1, matrix_2):
    matrix_1_shape = matrix_1.shape # 1つ目の行列の形
    matrix_2_shape = matrix_2.shape
    matrix_product_list = []

    if matrix_1_shape[0] != matrix_2_shape[1]:
        print("掛ける行列の行数と掛けられる行列の列数が等しくありません")
    else:
        for i in range(matrix_1_shape[0]):
            for j in range(matrix_2_shape[1]):
                matrix_product = np.sum(matrix_1[i,:]*matrix_2[:,j])
                matrix_product_list.append(matrix_product)
        matrix_product_re = np.reshape(matrix_product_list,(matrix_1_shape[0], matrix_2_shape[1]))
        return matrix_product_re

# 行列DE
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

compute_matrix_product(matrix_1 = d_ndarray, matrix_2 = e_ndarray)

掛ける行列の行数と掛けられる行列の列数が等しくありません


### 【問題6】転置

In [64]:
# 行列DE
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# np.transpose()

# 2つ目の行列を転置
f_ndarray = np.transpose(d_ndarray)
print(f_ndarray.shape)
print(e_ndarray.shape)
print(compute_matrix_product(matrix_1 = f_ndarray, matrix_2 = e_ndarray))

# .Tアトリビュート

# 2つ目の行列を転置
f_ndarray = d_ndarray.T
print(f_ndarray.shape)
print(e_ndarray.shape)
print(compute_matrix_product(matrix_1 = f_ndarray, matrix_2 = e_ndarray))

(3, 2)
(2, 3)
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
(3, 2)
(2, 3)
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
