# WEEK4授業前課題３　オブジェクト指向の活用

## 【問題1】これまで利用してきたクラスの列挙

クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

# pandasのクラス
pandas.DataFrame

# matplotlibのクラス
matplotlib.figure

# scikit-learnのクラス
sklearn.neighbors.KNeighborsClassifier<br>
sklearn.svm.SVC<br>
sklearn.cluster.KMeans


## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

《ndarrayやstrもインスタンス》

ドットをつけるというと、NumPyのndarrayに対してndarray.shapeやndarray.sum()のような使い方は何度も利用してきたかと思います。これは、ndarrayもインスタンスオブジェクトであり、shapeはインスタンス変数、sumはメソッドだったということです。

Pythonのコードに登場するデータはどれもインスタンスオブジェクトであり、listやstrもメソッドを持ちます。

In [1]:
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt

##numpy
print("numpy")
a = np.array([1,2,3])

print("インスタンス変数")
print(type(np.random.randn(100)))
print(type(a.dtype))

print("メソッド")
print(type(a.tolist))
print(type(a.astype))
print(type(a.sum))


##pandas
print("\npandas")
df = pd.DataFrame([1, 2, 3])

print("インスタンス変数")
print(type(df.columns))
print(type(df.index))
print(type(df.dtypes))
print(type(df.iloc))

print("メソッド")
print(type(df.head))



numpy
インスタンス変数
<class 'numpy.ndarray'>
<class 'numpy.dtype'>
メソッド
<class 'builtin_function_or_method'>
<class 'builtin_function_or_method'>
<class 'builtin_function_or_method'>

pandas
インスタンス変数
<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.indexing._iLocIndexer'>
メソッド
<class 'method'>


## 【問題3】標準化クラスをスクラッチで作成

理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。

インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [2]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X-self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [3]:
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


##  【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください

In [4]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
        
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        print(value2, "を足しました")
        self.value += value2
        print("value", example.value)
        
    def subtract(self, value3):
        """
        受け取った引数をself.valueから引く
        """
        print(value3, "を引きました")
        self.value -= value3
        print("value", example.value)
        
    def multiply(self, value4):
        """
        受け取った引数をself.valueにかける
        """
        print(value4, "をかけました")
        self.value *= value4
        print("value", example.value)
        
    def divide(self, value5):
        """
        受け取った引数でself.valueを割る
        """
        self.value /= value5
        print(value5, "で割りました")
        print("value", example.value)

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
example.subtract(3)
example.multiply(6)
example.divide(2)


初期値5が設定されました
value : 5
3 を足しました
value 8
3 を引きました
value 5
6 をかけました
value 30
2 で割りました
value 15.0


In [5]:
#エラーの確認
#配列を入力
example = ExampleClass(2)
example.add([3, 2])

初期値2が設定されました
[3, 2] を足しました


TypeError: unsupported operand type(s) for +=: 'int' and 'list'

In [ ]:
#エラーの確認
#文字列を入力
example = ExampleClass(2)
example.add("あいうえお")